package org.example.registry_service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-03T13:34:02.056+01:00
 * Generated source version: 2.5.0
 * 
 */
@WebService(targetNamespace = "http://www.example.org/registry_service/", name = "registry_service")
@XmlSeeAlso({ObjectFactory.class})
public interface RegistryService {

    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "NewOperation", targetNamespace = "http://www.example.org/registry_service/", className = "org.example.registry_service.NewOperation")
    @WebMethod(operationName = "NewOperation", action = "http://www.example.org/registry_service/NewOperation")
    @ResponseWrapper(localName = "NewOperationResponse", targetNamespace = "http://www.example.org/registry_service/", className = "org.example.registry_service.NewOperationResponse")
    public java.lang.String newOperation(
        @WebParam(name = "in", targetNamespace = "")
        java.lang.String in
    );
}
