package org.example.registry_service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.0
 * 2011-11-03T13:34:02.170+01:00
 * Generated source version: 2.5.0
 * 
 */
@WebServiceClient(name = "registry_service", 
                  wsdlLocation = "registry_service.wsdl",
                  targetNamespace = "http://www.example.org/registry_service/") 
public class RegistryService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/registry_service/", "registry_service");
    public final static QName RegistryServiceSOAP = new QName("http://www.example.org/registry_service/", "registry_serviceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("registry_service.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RegistryService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "registry_service.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RegistryService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegistryService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistryService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RegistryService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RegistryService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RegistryService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns RegistryService
     */
    @WebEndpoint(name = "registry_serviceSOAP")
    public RegistryService getRegistryServiceSOAP() {
        return super.getPort(RegistryServiceSOAP, RegistryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistryService
     */
    @WebEndpoint(name = "registry_serviceSOAP")
    public RegistryService getRegistryServiceSOAP(WebServiceFeature... features) {
        return super.getPort(RegistryServiceSOAP, RegistryService.class, features);
    }

}
